### ISSUE TITLE
【feat】设备中心：增加对单个已经废弃设备的删除，以及解除占用功能

### ISSUE THREAD

**Issue by upengfei** [ZhouYixun/sonic-server#70]
设备中心，增加对单个已经废弃设备的删除，以及解除占用功能

**Comment by upengfei** [comment]
如果临时需要在某一台机器上运行测试，刚好这台机器先前使用过，但是忘了退出，导致一直处于占用状态，无法进行测试。希望增加一个解除占用功能，应对这种情况。
2、随着时间的推移，有些机器可能不在使用，但是设备中心却一直存在，如果机型很多的话，导致查找，显示都不是很方便，希望增加删除功能，或者可自动显示或删除在线、离线设备
3、设备中心建议增加显示选项，只显示在线设备

**Comment by upengfei** [comment]
1、如果临时需要在某一台机器上运行测试，刚好这台机器先前使用过，但是忘了退出，导致一直处于占用状态，无法进行测试。希望增加一个解除占用功能，应对这种情况。
2、随着时间的推移，有些机器可能不在使用，但是设备中心却一直存在，如果机型很多的话，导致查找，显示都不是很方便，希望增加删除功能，或者可自动显示或删除在线、离线设备
3、设备中心建议增加显示选项，只显示在线设备

**Comment by ZhouYixun** [comment]
> 1、如果临时需要在某一台机器上运行测试，刚好这台机器先前使用过，但是忘了退出，导致一直处于占用状态，无法进行测试。希望增加一个解除占用功能，应对这种情况。 2、随着时间的推移，有些机器可能不在使用，但是设备中心却一直存在，如果机型很多的话，导致查找，显示都不是很方便，希望增加删除功能，或者可自动显示或删除在线、离线设备 3、设备中心建议增加显示选项，只显示在线设备

前两个可以做的，第三个的话，在【高级筛选】里面可以筛选在线状态的

**Comment by upengfei** [comment]
OK

**Comment by ZhouYixun** [comment]
[#44](https://github.com/ZhouYixun/sonic-client-web/issues/44)

这边有人先提出了，这边先关掉重复的需求了，你可以在那边关注进度
