### ISSUE TITLE
单机版启动失败

### ISSUE THREAD

**Issue by jahentao** [ZhouYixun/sonic-server#71]
```
docker-compose up
```
单机体验，默认配置外，要修改其他的吗
![1636330551(1)](https://user-images.githubusercontent.com/15883913/140667529-ea95ab40-b97c-4d4f-9bd6-935e6c84ce87.png)

**Comment by ZhouYixun** [comment]
> ```
> docker-compose up
> ```
> 
> 单机体验，默认配置外，要修改其他的吗 ![1636330551(1)](https://user-images.githubusercontent.com/15883913/140667529-ea95ab40-b97c-4d4f-9bd6-935e6c84ce87.png)

你好，请前往官网查看最新部署文档，有疑问可以通过官网【更多】->【联系我】->选择反馈群二维码，进群有很多部署成功的小伙伴帮你解答问题
