### ISSUE TITLE
【bug】测试用例没有执行完就退出连接！详情见截图

### ISSUE THREAD

**Issue by haojiguang88** [ZhouYixun/sonic-server#75]
![image](https://user-images.githubusercontent.com/44960818/141432682-c1d34bef-70a8-4571-bf0e-35741512c5be.png)
![image](https://user-images.githubusercontent.com/44960818/141432816-f2f1137a-ca63-494b-83a5-65cbb676dc8e.png)

**Comment by ZhouYixun** [comment]
fixed
