### ISSUE TITLE
【Bug】Galaxy Note20 UItra 页面布局异常

### ISSUE THREAD

**Issue by wangdan377** [ZhouYixun/sonic-server#89]
**Bug 描述**
清晰地描述Bug的情况与详细复现步骤 | A clear and concise description of what the bug is. 

**版本**
Sonic的版本号 | Sonic's Version. 
部署的系统(mac,windows32...) |  
![bfaac9baae7c61c0961558c64787bc4](https://user-images.githubusercontent.com/65341282/144559052-b85ac8f6-8c75-4b9c-ae3b-d73daca9ed7c.png)

**Comment by ZhouYixun** [comment]
已定位，下版本修复，感谢反馈
